/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const envPath = path.resolve(__dirname, '../../../.env.local');
dotenv.config({ path: envPath });

const SHIELD_MASK = "B4ST10N_PR0T0C0L";
const PREFIX = "SHIELD:";

function encode(input) {
  if (!input) return "";
  const clean = input.trim();
  if (clean.startsWith(PREFIX)) return clean;
  const hex = clean.split('').map((c, i) => {
    const code = c.charCodeAt(0) ^ SHIELD_MASK.charCodeAt(i % SHIELD_MASK.length);
    return code.toString(16).padStart(2, '0');
  }).join('');
  return PREFIX + hex;
}

const envModule = `// Auto-generated by build-env.js — DO NOT EDIT
if (!process.env.AWS_ACCESS_KEY_ID) process.env.AWS_ACCESS_KEY_ID = ${JSON.stringify(encode(process.env.AWS_ACCESS_KEY_ID || ''))};
if (!process.env.AWS_SECRET_ACCESS_KEY) process.env.AWS_SECRET_ACCESS_KEY = ${JSON.stringify(encode(process.env.AWS_SECRET_ACCESS_KEY || ''))};
if (!process.env.WG_US_PUBLIC_KEY) process.env.WG_US_PUBLIC_KEY = ${JSON.stringify(encode(process.env.WG_US_PUBLIC_KEY || ''))};
if (!process.env.WG_UK_PUBLIC_KEY) process.env.WG_UK_PUBLIC_KEY = ${JSON.stringify(encode(process.env.WG_UK_PUBLIC_KEY || ''))};
if (!process.env.WG_DE_PUBLIC_KEY) process.env.WG_DE_PUBLIC_KEY = ${JSON.stringify(encode(process.env.WG_DE_PUBLIC_KEY || ''))};
if (!process.env.WG_JP_PUBLIC_KEY) process.env.WG_JP_PUBLIC_KEY = ${JSON.stringify(encode(process.env.WG_JP_PUBLIC_KEY || ''))};
if (!process.env.WG_AU_PUBLIC_KEY) process.env.WG_AU_PUBLIC_KEY = ${JSON.stringify(encode(process.env.WG_AU_PUBLIC_KEY || ''))};
`;

const outPath = path.resolve(__dirname, '../electron/_env.js');
fs.writeFileSync(outPath, envModule);
console.log('✅ Build-time env embedded to electron/_env.js');
