import { describe, it, expect } from "vitest";
import {
  ADGUARD_DNS_SERVERS,
  DNS_PROVIDERS,
  DESKTOP_BLOCKLIST,
  generateDesktopSetupInstructions,
  generateHostsFileContent,
} from "./desktopAdBlock";

describe("ADGUARD_DNS_SERVERS", () => {
  it("has default, family, and unfiltered configurations", () => {
    expect(ADGUARD_DNS_SERVERS).toHaveProperty("default");
    expect(ADGUARD_DNS_SERVERS).toHaveProperty("family");
    expect(ADGUARD_DNS_SERVERS).toHaveProperty("unfiltered");
  });

  it("each config has ipv4 and ipv6 arrays", () => {
    for (const config of Object.values(ADGUARD_DNS_SERVERS)) {
      expect(config.ipv4).toBeInstanceOf(Array);
      expect(config.ipv6).toBeInstanceOf(Array);
      expect(config.ipv4.length).toBeGreaterThan(0);
      expect(config.ipv6.length).toBeGreaterThan(0);
    }
  });

  it("default DNS starts with 94.140", () => {
    expect(ADGUARD_DNS_SERVERS.default.ipv4[0]).toMatch(/^94\.140/);
  });
});

describe("DNS_PROVIDERS", () => {
  it("contains cloudflare and quad9 alternatives", () => {
    expect(DNS_PROVIDERS).toHaveProperty("cloudflare_malware");
    expect(DNS_PROVIDERS).toHaveProperty("quad9");
  });

  it("each provider has a description", () => {
    for (const provider of Object.values(DNS_PROVIDERS)) {
      expect(typeof provider.description).toBe("string");
      expect(provider.description.length).toBeGreaterThan(0);
    }
  });
});

describe("DESKTOP_BLOCKLIST", () => {
  it("contains ad-serving domains", () => {
    const blocklistStr = DESKTOP_BLOCKLIST.join(" ");
    expect(blocklistStr).toContain("doubleclick.net");
    expect(blocklistStr).toContain("googlesyndication.com");
    expect(blocklistStr).toContain("googleadservices.com");
  });

  it("contains social media trackers", () => {
    const blocklistStr = DESKTOP_BLOCKLIST.join(" ");
    expect(blocklistStr).toContain("facebook.com");
    expect(blocklistStr).toContain("ads-twitter.com");
  });

  it("contains analytics trackers", () => {
    const blocklistStr = DESKTOP_BLOCKLIST.join(" ");
    expect(blocklistStr).toContain("google-analytics.com");
    expect(blocklistStr).toContain("hotjar.com");
  });

  it("uses 0.0.0.0 sinkhole format", () => {
    for (const entry of DESKTOP_BLOCKLIST) {
      expect(entry).toMatch(/^0\.0\.0\.0 /);
    }
  });

  it("has a reasonable number of entries", () => {
    expect(DESKTOP_BLOCKLIST.length).toBeGreaterThan(30);
  });
});

describe("generateDesktopSetupInstructions", () => {
  it("generates DNS instructions with AdGuard IPs", () => {
    const instructions = generateDesktopSetupInstructions("dns");
    expect(instructions).toContain("94.140.14.14");
    expect(instructions).toContain("94.140.15.15");
    expect(instructions).toContain("Windows");
    expect(instructions).toContain("macOS");
    expect(instructions).toContain("Linux");
  });

  it("generates hosts file instructions with blocklist entries", () => {
    const instructions = generateDesktopSetupInstructions("hosts");
    expect(instructions).toContain("Hosts File");
    expect(instructions).toContain("0.0.0.0");
    expect(instructions).toContain("doubleclick.net");
  });
});

describe("generateHostsFileContent", () => {
  it("includes header with metadata", () => {
    const content = generateHostsFileContent();
    expect(content).toContain("# Ad Blocking Hosts File");
    expect(content).toContain("# Generated by");
    expect(content).toContain("# Entries:");
  });

  it("includes localhost entries", () => {
    const content = generateHostsFileContent();
    expect(content).toContain("127.0.0.1 localhost");
    expect(content).toContain("::1 localhost");
  });

  it("includes blocklist domains", () => {
    const content = generateHostsFileContent();
    expect(content).toContain("doubleclick.net");
    expect(content).toContain("googlesyndication.com");
  });
});
